# component detection for component governance checks
parameters:
- name: condition
  type: string
  default: 'succeeded' # could be 'ci_only', 'always', 'succeeded'

steps:
- ${{ if eq(variables['System.TeamProject'], 'Lotus') }}:
  - powershell: |
      Remove-Item $(Build.BinariesDirectory)/* -Recurse -Force
    displayName: 'Clean up build directory'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    continueOnError: true
    condition:
      or(or(and(eq('${{parameters.condition}}', 'ci_only'), and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Scheduled'))),
          and(eq('${{parameters.condition}}', 'always'), always())),
          and(eq('${{parameters.condition}}', 'succeeded'), succeeded()))
    inputs:
      # ignore cmake/external these are not our responsibility
      # ignore react_native e2e node_modules directory. react_native e2e node_modules directory is generated by react_native e2e tests
      # ignore github directory. github directory is used for github actions, not for onnxruntime package
      # ignore onnxruntime-inference-examples directory. onnxruntime-inference-examples directory is used for inference examples, not for onnxruntime package
      # ignore manylinux directory. manylinux is a third party directory, not responsible by onnxruntime
      # ignore BinariesDirectory. BinariesDirectory is used for build output, not for onnxruntime package
      ignoreDirectories:
        '$(Build.Repository.LocalPath)/cmake/external,
        $(Build.Repository.LocalPath)/js/react_native/e2e/node_modules,
        $(Build.Repository.LocalPath)/tools/ci_build/github,
        $(Build.SourcesDirectory)/onnxruntime-inference-examples,
        $(Build.SourcesDirectory)/manylinux,
        $(Build.BinariesDirectory)'