parameters:
  - name: EnvSetupScript
    type: string
  - name: DownloadCUDA
    type: boolean
  - name: DownloadTRT
    type: boolean
    default: false
  - name: PrimaryCUDAVersion
    type: string
    default: '11.8'
  - name: SecondaryCUDAVersion
    type: string
    default: '12.2'
  - name: ThirdCUDAVersion
    type: string
    default: '12.3'

steps:
  - ${{ if eq(parameters.DownloadCUDA, 'true') }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.PrimaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Primary CUDA SDK v${{ parameters.PrimaryCUDAVersion }}'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.SecondaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Secondary CUDA SDK v${{ parameters.SecondaryCUDAVersion }}'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.ThirdCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Third CUDA SDK v${{ parameters.ThirdCUDAVersion }}'
  

  - ${{ if eq(parameters.DownloadTRT, 'true') }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8" $(Agent.TempDirectory)
        displayName: 'Download TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0" $(Agent.TempDirectory)
        displayName: 'Download TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/TensorRT-10.0.0.6.Windows10.x86_64.cuda-12.4" $(Agent.TempDirectory)
        displayName: 'Download TensorRT-10.0.0.6.Windows10.x86_64.cuda-12.4'
      
  - task: BatchScript@1
    displayName: 'setup env'
    inputs:
      filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\${{ parameters.EnvSetupScript }}'
      modifyEnvironment: true
      workingFolder: '$(Build.BinariesDirectory)'
